### ISSUE TITLE
ValueError: no objects to update_or_create...

### ISSUE THREAD

**Issue by rtubio** [fopina/django-bulk-update-or-create#10]
I am now seeing the following exception when executing the bulk_update_or_create function, if there are no objects to be written to the database:

```
raise ValueError('no objects to update_or_create...')
ValueError: no objects to update_or_create...
```

Although this is easily fixable by just checking that the array to be passed to the function is not empty, the behavior is different to that from the standard update_or_create from Django's ORM.

Is there any reason why this is kept this way? In my opinion, it is different from the expectations of those used to work with Django.

**Comment by fopina** [comment]
done! thanks for the feedback 👍
