### ISSUE TITLE
multiple match_field not working in bulk_update_or_create_context

### ISSUE THREAD

**Issue by resakse** [fopina/django-bulk-update-or-create#26]
`bulk_update_or_create_context() got multiple values for argument 'match_field'
`

it working fine in normal bulk_update_or_create.
I've checked test file and it doesnt contain test for bulk_update_or_create_context with multiple match_field.

**Comment by fopina** [comment]
Can you provide the calls you made to both "_context" and "normal"?

**Comment by resakse** [comment]
I'm sorry, I dont have the code anymore since we decided to use bulk_create with ignore_conflicts=True. I guess I'll close this one since no one else complains.
