### ISSUE TITLE
comparison vs django-bulk-sync

### ISSUE THREAD

**Issue by sdementen** [fopina/django-bulk-update-or-create#7]
hello,

I am using django-bulk-sync to do the magic create or update in bulk.
Would you have tested your package against this one in terms of features & performances ?

**Comment by scorday** [comment]
I'm not sure completely, but in my case this lib is 3x faster than django-bulk-sync

**Comment by fopina** [comment]
Hey @sdementen sorry for the lack of response but no, I haven't compared against that package specifically.

Cheers @scorday !
